# Generated by Django 2.2.7 on 2019-11-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='bath_count',
            field=models.IntegerField(verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bed_count',
            field=models.IntegerField(verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='house',
            name='garage_size',
            field=models.CharField(choices=[('No Garage', 'No Garage'), ('1-Car Garage', '1-Car Garage'), ('2-Car Garage', '2-Car Garage'), ('3-Car+ Garage', '3-Car+ Garage')], default='No Garage', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='list_date',
            field=models.DateField(verbose_name='Date Listed'),
        ),
        migrations.AlterField(
            model_name='house',
            name='lot_size',
            field=models.IntegerField(verbose_name='Lot Size (Acres)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='mls_num',
            field=models.IntegerField(unique=True, verbose_name='MLS Number'),
        ),
        migrations.AlterField(
            model_name='house',
            name='sales_price',
            field=models.IntegerField(verbose_name='Sales Price'),
        ),
        migrations.AlterField(
            model_name='house',
            name='sq_ft',
            field=models.IntegerField(verbose_name='Square Footage'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street1',
            field=models.CharField(max_length=100, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street2',
            field=models.CharField(max_length=50, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='house',
            name='zip_code',
            field=models.IntegerField(verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='house',
            name='photos',
            field=models.ManyToManyField(to='realtor.HousePhoto'),
        ),
    ]
