# Generated by Django 2.2.7 on 2019-11-20 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_auto_20191120_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='photos',
        ),
        migrations.AddField(
            model_name='housephoto',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realtor.House'),
        ),
    ]
